### PR TITLE
P dharmesh autoit

### PR DESCRIPTION
**Pull request by dharmesh4**
Attempting to merge AutoIt engine changes to master.

### CODE REVIEW

**Comment by sascanagl** [comment]
I'm going to start adding the DriverInterface changes and other associated changes that makes this work for all of SAFS and NOT just SeleniumPlus and JSAFSDriver.

**Comment by sascanagl** [comment]
I believe I have addressed all the issues mentioned above.  I have also added a significant amount of comments and JavaDoc.  

However, I'm not currently setup to test these changes.  Please take the updates and verify the existing tests still pass/run successfully.

**Comment by dharmesh4** [comment]
I will check before the merge the code. Thanks a lot

**Comment by dharmesh4** [comment]
Code merged to master

**Pull request merged**
